### ISSUE TITLE
Users should not be able to reserve 2 consecutive timeslots

### ISSUE THREAD

**Issue by PimClappers** [DavidBergevoet/Setup-Reservation#4]
When a user has placed a reservation, he or she should not be able to place a second reservation immediately afterwards. Currently, users can reserve an unlimited amount of time by spamming the reserve button. See image below. (Name is censored for privacy reasons).
Ofcourse, a user could still reserve a second time slot under a different name. Maybe prevent multiple reservations by checking the ip-adress of the user?
![Screenshot_20240607_160819_WhatsApp](https://github.com/DavidBergevoet/Setup-Corn-Reservation/assets/37137643/0f853700-0a18-42d6-a1db-5b93e02bd08b)

**Comment by InzeNL** [comment]
@DavidBergevoet 

For the "maximum time", how do we deal with that? Look at this example:
1. You can reserve a maximum of 60 minutes
2. I place a reservation for 60 minutes
3. 30 minutes in, I want to place another reservation

Do I have to wait for the full reservation to pass, or can I, at this point, reserve 30 more minutes?
